### PR TITLE
为新开发人员简化打码

### PR DESCRIPTION
**Pull request by jankeromnes**
👋 你好，
我的中文不好，对不起。🙏

我为py12306配置了Gitpod。
Gitpod支持免费打码，这对初学者有好处。
请试一试：

[Open in Gitpod](https://gitpod.io#https://github.com/jankeromnes/py12306)
screenshot 2019-01-21 at 19 57 58

### CODE REVIEW

**Comment by Hamishcn** [comment]
hello, connection to gitpod in China Mainland without tunnel can be very slow due to the firewall, I think this is not good for this repo since it's mostly used by people in China Mainland.

**Comment by pjialin** [comment]
Thanks for the pull-request, as @Hamishcn said, At China situation, I can't visit gitpod.io without the tunnel, but I tested in Gitpod,  it runs well. so I'll put a link at the bottom of the readme, for everyone who wants to try that

**Comment by jankeromnes** [comment]
Hello @Hamishcn and @pjialin, thank you so much for your feedback! 🙏 And thank you for reporting the connection problems to Gitpod. 😕 We really want to make Gitpod useful for your project, and gitpod.io has servers in Taiwan, so I hope the connection is fast enough in Mainland China. But maybe gitpod.io is blocked by the firewall?

**Comment by Hamishcn** [comment]
@jankeromnes hello, I tested that on local network and server network, that showed the connection to gitpod.io could be established but was very slow to load pages, mtr showed pakcet loss% is up to 70%. The firewall may not blocked.

**Comment by jankeromnes** [comment]
Wow, 70% packet loss is bad. So sorry about that, and again, many thanks for helping us understand this problem. Do you know if your requests were routed to Taiwan / or to the United States / or to Europe? The workspace URL should also say "ws-ap" (not "ws-us" or "ws-eu").

**Comment by Hamishcn** [comment]
according to WinMTR, the connection start from my local network and turns to Guangzhou, then Hongkong and eventually connects to United States.

**Comment by jankeromnes** [comment]
Many thanks. The United States endpoint could explain the big packet loss. We probably need to fix Gitpod's routing for Mainland China. I'll let you know if we can fix it. Thanks again! 👍 💯

**Pull request merged**
